### ISSUE TITLE
Project dead? How about the GC?

### ISSUE THREAD

**Issue by olleharstedt** [raph-amiard/CamllVM#7]
Hi!

Did you ever get the OCaml GC to work with LLVM? I'm working on such a project now and I'm having some difficulties with this. Do you know any project that successfully integrated LLVM with the OCaml GC?

Regards
Olle

**Comment by raph-amiard** [comment]
Hello Olle,

I never succeeded indeed in integrating the GC with the "fast" branch of this project. There are two problems here:
1. I'm emitting phi nodes manually instead of using alloca + the mem2reg pass, which is the canonical way, and is pretty much needed by any gc pass LLVM has AFAIK.
2. The old support for GC in LLVM was not powerful enough to handle a GC such as OCaml's from what I can tell, not with a lot of gymnastics. The main problem was the interaction with real machine registers. There is a new facility since LLVM 3.8 called statepoints : http://llvm.org/docs/Statepoints.html that should be powerful enough.

Anyway this would pretty much require a full rework of this project, so except if I have an unexpected two months holiday coming up, I'll not be able to make it :)

**Comment by olleharstedt** [comment]
Did you integrate the project with _any_ GC algorithm?

**Comment by raph-amiard** [comment]
Yes, the boehm branch runs the optimized code emitter against the boehm GC, while the explicit-stack branch uses the OCaml GC but has a much less optimized code generator that doesn't really translate the bytecode to LLVM semantics, but rather reuses the VM stack and facilities.

**Comment by olleharstedt** [comment]
Ah, and the explicit stack method would kind of correspond to the `CAMLlocal()` macros in the OCaml C API? Because I have been thinking about generating C-code instead of LLVM, but that would leave you less possibilities for optimizations further down the road.
